### ISSUE TITLE
Child Panes in Nested Layouts not respecting ToolTip Defaults

### ISSUE THREAD

**Issue by melloware** [allpro/layout#16]
I have an example page here:   http://www.primefaces.org/showcase-ext/sections/layout/fullPageAttr.jsf

I have set the default option of togglerTip_closed = "Close Me".    If hove over the close on the outside panes you see the tooltip is "Close Me", however if you hover over any of the internal panes like West North or West-South you see it has the default "Close".

**Comment by melloware** [comment]
@GedMarc can you look at this on your fork?  I have been using your forked version because you have all the Jquery 3.0 fixes in there.

**Comment by GedMarc** [comment]
Sure thing, will let you know what I find

**Comment by GedMarc** [comment]
So the fields you are using come from a very old version of layout - 

They are only working on the outside layout because that's when the values get over-ridden.
When the child layouts are created, these are discarded. 

I think removing the backwards compatibility options (finally) rather than implement it on the children could work?

These are the changes I think you are looking for

tips: {
                Open: "Open"  // eg: "Open Pane"
                , Close: "Close"
                , Resize: "Resize"
                , Slide: "Slide Open"
                , Pin: "Pin"
                , Unpin: "Un-Pin"
                , noRoomToOpen: "Not enough room to show this panel." // alert if user tries to open a pane that cannot
                , minSizeWarning: "Panel has reached its minimum size" // displays in browser statusbar
                , maxSizeWarning: "Panel has reached its maximum size" // ditto
            }

Also please use the defaults {} rather than "panes"

$('#body').layout(
        {
            **defaults: {**
                tips : {
                Open: "Open Me Test",
                Close: "Close Me Test"
}
                west: {
                    spacing_open: 6,
                    spacing_closed: 6,
                    size: 200,
                    childOptions:
                            {
                                north: {
                                    spacing_open: 6,
                                    spacing_closed: 6,
                                    size: "33%"},
                                south: {spacing_open: 6,
                                    spacing_closed: 6,
                                    initClosed: true,
                                    size: "33 %" //west init incorrect
                                },
                                center: {
                                    minHeight: 60,
                                    spacing_open: 6,
                                    spacing_closed: 6}
                            }
                }
            }
        }
);

Also check the 33% :)

**Comment by allpro** [comment]
**The result described is as designed.** Nested layouts integrate their sizing, but other than that all layouts are independent. Options set in one layout **_do not_** cascade to child layouts. Your demo only has a `panes.togglerTip` option in the outer-layout, therefore only that layout has those custom tips.

If you have standard options for multiple layouts, you can set these in a hash and use them as _base options_ for each layout. For example:

```javascript
var commonOptions = { 
    panes: {
        "togglerTip_open": "Close Me", 
        "togglerTip_closed": "Open Me", 
        "resizerTip": "Resize Me"
    }
};

var layoutOpts1 = $.extend( true, {}, commonOptions, { ... } );
var layoutOpts2 = $.extend( true, {}, commonOptions, { ... } );
```

If you want to update ALL layouts on a page, the simplest option is to modify the layout defaults, like:
```javascript
$.extend( true, $.layout.defaults, {
    panes: {
        "togglerTip_open": "Close Me", 
        "togglerTip_closed": "Open Me", 
        "resizerTip": "Resize Me"
    }
});
```

You can still override both defaults and commonOptions in the options of each layout.

**Comment by allpro** [comment]
If the fork mentioned cascades tooltip options, that's fine, but it's may be more expressive to change the defaults instead.

Note that pane-specific options (eg: 'west') _override_ generic options ('panes'). While it may be useful to cascade the 'panes' options, it probably does not make sense to cascade the pane-specific options, because they are 'specific'.

**Comment by GedMarc** [comment]
Panes is a back reference, please don't use it :)

The syntax you are using is from 1.2, the version on the example page is 1.4.2. The syntax was placed as backwards compatible in version 1.3.3.

Also please use defaults and place all default values in there, this is from ages ago.
The above would look like :

$("container").layout{{
defaults : {
  tips : {
 Open : "Close Me",
 Close : "Close Me",
Resize : "Resize Me"
 }
 }
}
}

Please see the following reference in the source

/**
         * Initialize nested layouts for a specific pane - can optionally pass layout-options
         *
         * @param {(string|Object)} evt_or_pane The pane being opened, ie: north, south, east, or west
         * @param {Object=}   [opts]  Layout-options - if passed, will OVERRRIDE options[pane].children
         * @return  An object pointer to the layout instance created - or null
         */
        , createChildren = function (evt_or_pane, opts)

**Comment by melloware** [comment]
Where is the reference for the new options.  I am still using this site and it talks about toggerTip_Closed still?

http://layout.jquery-dev.com/documentation.cfm#Options

**Comment by GedMarc** [comment]
Yes sorry about that, I know Kevin is very busy although he has managed a bit of updates to the git site

https://groups.google.com/forum/#!forum/jquery-ui-layout
> 
> UI Layout Links
>     Source Code +
>     Demos
>     Documentation **(currently outdated, from version 1.2.0)**
>     Tips & FAQ

There are still a few items outstanding in the bug list for that git version, mostly related to JQuery 3 support as well as bootstrap support.

I've  been doing my best to keep it up to date as they all come in but all in all it is very stable and still the best layout handler.
My specific fork is here https://github.com/GedMarc/layout, mostly css additions, removed all the demo things and added responsiveness.

**Comment by GedMarc** [comment]
I can't get a hold of Kevin right now - I'll see if I can upload the documentation somewhere

**Comment by GedMarc** [comment]
This one looks good 👍

http://layout.jquery-dev.com/demos/complex.html

**Comment by melloware** [comment]
Thanks for thank link!  Awesome.  I will update my app to use the new settings and report back.

**Comment by GedMarc** [comment]
Please use this reference specific to 1.4
If you need a 1.5 version let me know

[JQuery Layout 1.4 Default Options.txt](https://github.com/allpro/layout/files/655403/JQuery.Layout.1.4.Default.Options.txt)

**Comment by melloware** [comment]
Thanks for that.  Here is what is interesting.  It seems to work for first class panes but this code is trying to use "children" or "childOptions" show below.  The children do not respect the togglerTip_Close.  This code I have take over started in 2011 and it appear the children options work but that is the bug where the tooltip is not being respected.  Any thoughts?

```
options:{
   "defaults":{
      "resizerTip":"Resize Me",
      "togglerTip_open":"Close Me",
      "togglerTip_closed":"Open Me"
   },
   "north":{
      "spacing_closed":6,
      "size":"80",
      "closable":false,
      "spacing_open":6
   },
   "south":{
      "spacing_closed":6,
      "size":"80",
      "spacing_open":6
   },
   "west":{
      "spacing_closed":6,
      "size":"200",
      "spacing_open":6,
      "children":{
         "north":{
            "spacing_closed":6,
            "size":"33%",
            "spacing_open":6,
            "togglerTip_closed":"Close me!!!"
         },
         "south":{
            "spacing_closed":6,
            "size":"33%",
            "spacing_open":6,
            "initClosed":true
         },
         "center":{
            "minHeight":"60",
            "spacing_closed":6,
            "spacing_open":6
         }
      }
   },
   "east":{
      "spacing_closed":6,
      "size":"200",
      "spacing_open":6,
      "resizeWhileDragging":true
   },
   "center":{
      "spacing_closed":6,
      "spacing_open":6,
      "children":{
         "north":{
            "spacing_closed":6,
            "size":"50%",
            "spacing_open":6,
            "togglerTip_closed":"Close me!!!"
         },
         "center":{
            "minHeight":"60",
            "spacing_closed":6,
            "spacing_open":6
         }
      }
   }
}
```

**Comment by GedMarc** [comment]
[layout try this.txt](https://github.com/allpro/layout/files/655537/layout.try.this.txt)

**Comment by GedMarc** [comment]
The other way of course is to initialize the two layouts separately

**Comment by GedMarc** [comment]
[layout try this.txt](https://github.com/allpro/layout/files/655545/layout.try.this.txt)

**Comment by GedMarc** [comment]
Can this be closed? :)

**Comment by melloware** [comment]
Let me try it first before you close it.

**Comment by melloware** [comment]
Confirmed you can close this.  Thanks for the help!

**Comment by GedMarc** [comment]
Remember to mark successful :)

**Comment by allpro** [comment]
> Panes is a back reference... The syntax was placed as backwards compatible in version 1.3.3

_Actually_ it is the other way around. **Setting options.defaults is supported for backward compatibility, but the _correct key_ is options.panes.** 

This change was made when the default-options were exposed as **`$.layout.defaults`**. To avoid the confusing path: **`$.layout.defaults.defaults`**, this change made it: **`$.layout.defaults.panes`**.

**Comment by melloware** [comment]
@allpro I was able to get it all working and actually made my code more flexible by allowing users to change tooltips per pane anyway.  Thanks for all the help and great plugin!

**Comment by melloware** [comment]
@GedMarc Using your fork I had a user report this issue.  https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/448
