### ISSUE TITLE
JQuery 3.x $.parseJson

### ISSUE THREAD

**Issue by melloware** [allpro/layout#19]
$.parseJson is now JSON.parse in JQuery 3.x

https://github.com/jquery/jquery-migrate/blob/master/warnings.md

JQMIGRATE: jQuery.parseJSON is deprecated; use JSON.parse

Cause: The jQuery.parseJSON method in recent jQuery is identical to the native JSON.parse. As of jQuery 3.0 jQuery.parseJSON is deprecated.

Solution: Replace any use of jQuery.parseJSON with JSON.parse.

**Comment by GedMarc** [comment]
Thanks @melloware

**Comment by melloware** [comment]
No prob!  I was fixing another component I use and saw this migration hint and figured you guys would be interested.  Once again thanks for all your amazing work!
