### ISSUE TITLE
Error due to incomplete if-else if-else statement

### ISSUE THREAD

**Issue by djwashburn** [allpro/layout#24]
In commit af0863f24404bb54d0e7d12b6930e4e475d0055a of the https://github.com/GedMarc/layout fork, a bug is introduced at the if-else if-else that begins  `if (s.isClosed || s.isResizing)` in slideClose in the jquery.layout_and_plugins. The syntax is wrong, because there is no statement after the if, and no open and close brackets in place of the statement that was removed.

**Comment by GedMarc** [comment]
Not quite, The syntax is correct - blame safari for that one.

Are you having any issues at all?

**Comment by GedMarc** [comment]
https://github.com/allpro/layout/blob/7f0c5f7b1a9f9290efe9abbc5bf660a9debf8d79/source/stable/jquery.layout_and_plugins.js#L3692
Please refer to the original code base

**Comment by djwashburn** [comment]
I am having an issue, it comes up as a syntax error in chrome, which fails to read the file after that point. While it is true that you can omit brackets in an if-else, there must be a statement after each if - either a single statement, or a block wrapped in curly brackets. Since the single statements were removed, leaving only comments, Javascript is seeing only `if (condition) else if (condition)`, and I get a complaint about "unexpected token else", because there needs to be a statement after the if and before the else.

That's one reason using curly brackets is preferred to omitting them - it's less brittle when code is changed. Though I am aware you are not the original author, I'm not blaming you.

**Comment by djwashburn** [comment]
Is it possible to allow issue tracking within your fork, since this stable jQuery 2 branch is no longer maintained? It is confusing not to be able to create issues in the fork where they occur.

**Comment by GedMarc** [comment]
I had not realized that was the case,
I have ticked the box :)

**Comment by GedMarc** [comment]
Can you let me know which browser you are receiving this error on?
If it's an update to a JS Engine then I will need to look at this, when Chrome went to 54 there were a ton of changes that had unwanted effects

**Comment by GedMarc** [comment]
No Reply

**Comment by djwashburn** [comment]
It happens in Chrome - I have Chrome 67
